language: clojure
lein: lein2
before_install:
    - lein2 bootstrap
install:
    - lein2 check
script:
    - lein2 with-profile +test do eastwood, midje
after_success:
    - lein2 with-profile +test cloverage --coveralls --no-html
